spring:
  application:
    name: notification-service
  profiles:
    active: default
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}/eureka/

fcm:
  certification: firebase/certification.json
